---
# This playbook does a rolling update for all webservers serially (one at a time).
# Change the value of serial: to adjust the number of server to be updated.
#
# The three roles that apply to the webserver hosts will be applied: common,
# base-apache, and web. So any changes to configuration, package updates, etc,
# will be applied as part of the rolling update process.
#

# gather facts from monitoring nodes for iptables rules
- hosts: monitoring
  tasks: []

- hosts: webserver
  user: root
  serial: 1

  # These are the tasks to run before applying updates:
  pre_tasks:
  - name: notify newrelic of deployment
    shell: action=disable_alerts host={{ inventory_hostname }} services=webserver
    delegate_to: "{{ item }}"
    with_items: groups.monitoring

  - name: disable the server in haproxy
    shell: echo "disable server myapplb/{{ inventory_hostname }}" | socat stdio /var/lib/haproxy/stats
    delegate_to: "{{ item }}"
    with_items: groups.lbservers

  roles:
  - deploy

  # These tasks run after the roles:
  post_tasks:
  - name: Wait for webserver to come up
    wait_for: host={{ inventory_hostname }} port=8080 state=started timeout=80

  - name: Enable the server in haproxy
    shell: echo "enable server myapplb/{{ inventory_hostname }}" | socat stdio /var/lib/haproxy/stats
    delegate_to: "{{ item }}"
    with_items: groups.lbservers

  - name: notify newrelic of success
    shell: action=enable_alerts host={{ inventory_hostname }} services=webserver
    delegate_to: "{{ item }}"
    with_items: groups.monitoring
