---
- name: packages | update
  apt:
    update_cache=yes
    cache_valid_time=36000
  tags: install
  sudo: true

- name: packages | ensure core packages are installed | deb
  apt:
    pkg={{ item }}
    state=installed
  tags: install
  sudo: true
  with_items:
    - atop
    - curl
    - git
    - htop
    - iotop
    - make
    - socat
    - ssh-import-id
    - strace
    - systemtap
    - unzip
    - vim
