---

hostname: "{{ inventory_hostname }}"
secondary_hostname: 127.0.0.1
secondary_hostname_language: en
http_port: 80

admin: {'username' : 'admin', 'password': 'admin', 'email': 'vagrant@localhost'}

shared_path: "/data/shared"
nfs_shared_path: "{{ shared_path }}/nfs"
log_shared_path: "{{ shared_path }}/log"
backup_path: "{{ shared_path }}/backup"
cache_path: "/data/shared/cache"
local_cache: "/tmp/cache"

email_domain: "localhost"
email_domain_access: "localhost"
email_from: "no-reply@{{ email_domain }}"
error_email_from: "error@{{ email_domain }}"

admin_email: vagrant@localhost
error_email: "{{ admin_email }}"

## Web config
www_root: "{{ shared_path }}/assets }}"
www_user: www-data
www_group: www-data

## SSL config
certificates_path: "{{ shared_path }}/ssl"
basic_auth_path: false

ssl: true
ssl_port: 443
ssl_path: false #"{{ certificates_path }}"
ssl_crt_primary: server.crt
ssl_crt_secondary: server.crt
ssl_key_primary: server.key
ssl_key_secondary: server.key
ssl_pem: "{{ ssl_crt_primary }}.pem"

## App server config
app_port: 8080
java_home: /usr/lib/jvm/java-7-openjdk-amd64
webapps_path: /usr/share/jetty/webapps
app_name: sample
app_war: "{{ shared_path }}/{{ app_name}}.war"
war_sha256sum: 89b33caa5bf4cfd235f060c396cb1a5acb2734a1366db325676f48c5f5ed92e5
