---

# Haproxy config
haproxy_user: "root"



haproxy_global:
  chroot: true
  pidfile: "{{ shared_path }}/haproxy.pid"
  maxconn: 1000
  user: "{{ haproxy_user }}"
  group: "{{ haproxy_user }}"
  daemon: true
  spread_checks: true
  stats:
      socket: "{{ shared_path }}/haproxy.sock"
  log:
    - address: "{{ log_shared_path }}/haproxy.log"
      facility: syslog
      level: warn
      minlevel: warn
      format: http

haproxy_defaults:
  mode: http
  log: http
  # options:
  #   - <option>
  retries: 5
  # timeout:
  #   - param: 
  #     value:
  maxconn: 1000
  # stats:
  #   enabled: true
  #   hide_version: true
  #   uri: 
  #   realm:
  #   auth:
  #   refresh:

haproxy_frontends:
  - name: http
    ip: 0.0.0.0
    bind: "*:80"
    maxconn: 1000
    # monitor: 
    #   uri:
    #   fail:
    #     - <condition>
    acl:
      - name: rule1
        condition: hdr_dom(host) -i www.{{ ansible_hostname }} -i app.{{ ansible_hostname }}
      - name: rule2
        condition: hdr_dom(host) -i static.{{ ansible_hostname }}
    # rate-limit-sessions:
    # block:
    #     - 
    default_backend: jetty
    use_backend:
      - name: jetty
        condition: rule1
    use_backend:
      - name: nginx
        condition: rule2

haproxy_backends:
  - name: nginx
    disabled: false
    description: "{{ item.name }}"
    balance: 100
    log: "{{ log_shared_path }}/{{ item.name }}"
    retries: 3
    contimeout: 20
    http-send-name-header: true
    # http-check-expect:
    #     - condition
    # acl:
    #   - name:
    #     condition:
    servers:
      - name: "{{ item.name }}-01"
        ip: "{{ item.name }}-01"
        port: "{{ http_port }}"
        maxconn: 1000
        params:
              - param1
      - name: "{{ item.name }}-02"
        ip: "{{ item.name }}-02"
        port: "{{ http_port }}"
        maxconn: 1000
        params:
              - param1
    options:
        - forwardfor

  - name: jetty
    disabled: false
    description: "{{ item.name }}"
    balance: 100
    #log: "{{ log_shared_path }}/{{ item.name }}"
    retries: 3
    contimeout: 20
    http-send-name-header: true
    # http-check-expect:
    #     - condition
    # acl:
    #   - name:
    #     condition:
    servers:
      - name: "{{ item.name }}-01"
        ip: "{{ item.name }}-01"
        port: "{{ http_port }}"
        maxconn: 1000
        params:
              - param1
      - name: "{{ item.name }}-02"
        ip: "{{ item.name }}-02"
        port: "{{ http_port }}"
        maxconn: 1000
        params:
              - param1
    options:
        - forwardfor
