---

# - name: backup old warfile
#   copy: src="{{ webapps_dir }}/{{ app_name }}.war" dest="{{ webapps_dir }}/{{ app_name }}.backup"
#   tags:
#   - deploy

- name: download warfile
  get_url:
    url={{ app_war }}
    dest={{ webapps_dir }}
    sha256sum={{ war_sha256sum }}
  tags:
  - deploy

- name: ensure ownership
  shell: chown {{ www_user }}:{{ www_group }} "{{ webapps_dir }}" && chmod -R u+rwX,g+rwX,o-rwx "{{ webapps_dir }}"
  notify: restart jetty
  tags:
  - deploy
