---

- name: ensure nginx is installed
  apt: 
    pkg="nginx"
    state=latest
  tags:
    - nginx
    - packages

- name: copy base nginx configuration
  template:
    src="nginx.conf.j2"
    dest=/etc/nginx/nginx.conf
    mode=0644
    owner=root
    group=root
  tags:
    - nginx

- name: remove default site
  file:
    path="/etc/nginx/sites-enabled/default"
    state=absent
  tags:
    - nginx
  notify:
    - restart nginx

- name: copy nginx sites
  template:
    src={{ item.template }}
    dest=/etc/nginx/{{ item.destination }}
    mode=0644
    owner=root
    group=root
  with_items:
    - { 'template':'nginx_site_config.j2','destination':"sites-available/{{ nginx_app }}", 'ssl_crt': "{{ ssl_crt_primary }}", 'ssl_key': "{{ ssl_key_primary }}", 'server_name': "{{ hostname }}", 'root_redirect': false }
  tags:
    - nginx

- name: enable nginx site
  file:
    src="/etc/nginx/sites-available/{{ item }}"
    dest="/etc/nginx/sites-enabled/{{ item }}"
    state=link
  with_items:
    - "{{ nginx_app }}"
  tags:
    - nginx
  notify:
    - restart nginx

