---

- hosts: appserver
  sudo: true
  gather_facts: false
  vars_files:
    - "vars/common.yml"
    - ["vars/secrets/{{ secret_variables }}", "vars/none.yml"]
    - ["vars/local.yml", "vars/none.yml"]
  roles:
    - common
    - jetty
    - clamav
    #- nfs_server
    #- postfix

