---

- hosts: webserver
  sudo: true
  vars_files:
    - "vars/common.yml"
    - ["vars/secrets/{{ secret_variables }}", "vars/none.yml"]
    - ["vars/local.yml", "vars/none.yml"]
  roles:
    - common
    - firewall
    - users
    - ssl
    - nginx
    - clamav
    #- postfix

